# Generated by Django 5.0.2 on 2024-05-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profileIcon.jpg', upload_to='profile_pics'),
        ),
    ]
