# Generated by Django 5.0.2 on 2024-05-20 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='item_image',
            field=models.CharField(default='https://images.app.goo.gl/7AShWbgLpLZJf9d36', max_length=500),
        ),
    ]
