# Generated by Django 5.0.2 on 2024-05-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_items_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='item_image',
            field=models.CharField(default='food/food-placeholder.jpg', max_length=500),
        ),
    ]
